chat/urls.py
from django.urls import path


from . import views
app_name = 'chats'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    path('start_chat/<str:username>', views.start_chat, name="start_chat"),
]

cihadproje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from home.views import home_view
from post.views import post_index
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_index, name='home'),
    path('post/',include('post.urls')),
    path('users/', include('users.urls')),
    path('chat/', include('chat.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
#from home.views import home_view
from .views import *

app_name='post'

urlpatterns = [
    path('index', post_index),
    path('user_index', user_post_index, name='userindex'),
    path('<int:id>', post_detail, name='detail'),
    path('create', post_create, name='create'),
    path('<int:id>/update', post_update, name='update'),
    path('<int:id>/delete', post_delete, name='delete'),
    path('category', category_view, name='category'),
    path('category/<int:category_id>', category_index_view, name='category_index'),
]

users/urls.py
from django.urls import path
from .views import *


app_name = 'users'

urlpatterns = [
    path('profile', profile_view, name='profile'),
    path('login', login_view, name='login'),
    path('register', register_view, name='register'),
    path('logout', logout_view, name='logout'),
    path('logout', logout_view, name='logout'),
    path('edit', editprofile_view, name='edit'),
    path('<str:username>', user_profile_view, name='userprofile')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, render

def home_view(request):
    return render(request, 'home.html', {})

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>2.ELCİ</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
   {% include 'header.html' %}

    {% block body %}

    {% endblock %}

   <script type="text/javascript" src="{% static 'js/jquery-3.6.0.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/form2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
 <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1>Ürün Oluştur</h1>
                    {{ form|crispy }}

                    <input type="submit" value="Ürün Oluştur">
                </form>
            </div>
        </div>
 </div>


{% endblock %}

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand " href="{% url 'home' %}">2.El Al/Sat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav">


        <li class="nav-item-active">
            <a class="nav-link" href="{% url 'home' %}"> Ana Sayfa</a>
        </li>
          <li class="nav-item-active">
            <a class="nav-link" href="{% url 'post:category' %}"> Kategoriler</a>
        </li>
    </ul>
    <ul class="navbar-nav ms-auto">

      {% if not request.user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'users:register' %}">Üye Ol</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'users:login' %}">Giriş Yap</a>
      </li>
      {% else %}
            {% if user.avatar %}
            <li class="nav-item active">
                <a class="" href="{% url 'users:profile' %}"><img class="rounded-circle text-center" src="{{request.user.avatar.url}}" width="40" height="40"></a>
            </li>
            {% endif %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:profile' %}">{{request.user.username.capitalize}}</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'post:create' %}">Ürün Ekle</a>
            </li>
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'post:userindex' %}">Ürünlerim</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'chats:index' %}">Mesaj</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:logout' %}">Çıkış Yap</a>
            </li>
      {% endif %}
        <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control me-2" type="text" name="q" placeholder="Arama yap..." value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <button class="btn btn-outline-success" type="submit">Ara</button>
                    </span>
                </div>
            </form>
    </ul>
  </div>

</nav>

templates/home.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<div class="row">
           {% for post in posts %}
    <div class="col d-flex align-items-stretch">

        <div class="card text-white bg-dark mb-2" style="width: 15rem;height 10rem;">
        <img class="card-img-top" src="{{ post.post_image.url }}" alt="Card image cap" width="290" height="200">
         <div class="card-body">
             <h3 class="card-title"><b>{{ post.title }}</b></h3>
             <h5>{{ post.category }}</h5>
             <small>{{post.adress}}</small>

             <h2 class="card-title"><b>{{ post.price }} ₺</b></h2>
        <a href="{{ post.get_absolute_url }}" class="btn btn-danger btn-lg align-bottom" style="">Ürün Detayları</a>
             <br><small>{{post.created_time}}</small><br>
         </div>
    </div>


    </div>
            {% endfor %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3"
                <div class="pagination">
                <span class="step-links">
                    {% if posts.has_previous %}
                        <a href="?page=1">&laquo; İlk sayfaya git</a>
                        <a href="?page={{ posts.previous_page_number }}">Önceki</a>
                    {% endif %}

                    <span class="current">
                        {{ posts.number }}/{{ posts.paginator.num_pages }}. Sayfa
                    </span>

                    {% if posts.has_next %}
                        <a  href="?page={{ posts.next_page_number }}">Sonraki</a>
                        <a href="?page={{ posts.paginator.num_pages }}">En son &raquo;</a>
                    {% endif %}
                </span>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}