chat/urls.py
from django.urls import path


from . import views
app_name = 'chats'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    path('start_chat/<str:username>', views.start_chat, name="start_chat"),
]

cihadproje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from home.views import home_view
from post.views import post_index
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_index, name='home'),
    path('post/',include('post.urls')),
    path('users/', include('users.urls')),
    path('chat/', include('chat.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
#from home.views import home_view
from .views import *

app_name='post'

urlpatterns = [
    path('index', post_index),
    path('user_index', user_post_index, name='userindex'),
    path('<int:id>', post_detail, name='detail'),
    path('create', post_create, name='create'),
    path('<int:id>/update', post_update, name='update'),
    path('<int:id>/delete', post_delete, name='delete'),
    path('category', category_view, name='category'),
    path('category/<int:category_id>', category_index_view, name='category_index'),
]

users/urls.py
from django.urls import path
from .views import *


app_name = 'users'

urlpatterns = [
    path('profile', profile_view, name='profile'),
    path('login', login_view, name='login'),
    path('register', register_view, name='register'),
    path('logout', logout_view, name='logout'),
    path('logout', logout_view, name='logout'),
    path('edit', editprofile_view, name='edit'),
    path('<str:username>', user_profile_view, name='userprofile')
]

post/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    yazar = models.ForeignKey('users.CustomUser', verbose_name='yazar', on_delete=models.CASCADE,related_name='posts')
    title = models.CharField(max_length=120,verbose_name='Başlık')
    description = models.TextField(blank=True,null=True,verbose_name='Açıklama')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,blank=True,null=True,verbose_name='Kategori')
    post_image = models.ImageField(null=True, blank=True, default='default_product.png',verbose_name='Resim')
    created_time = models.DateTimeField(auto_now_add=True)
    price = models.IntegerField(verbose_name='Fiyat',default="1")
    adress = models.CharField(max_length=300,null=True, blank=True,default="Adres Belirtilmedi", verbose_name='Adres')
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'id': self.id})

class Category(models.Model):
    name = models.CharField(max_length=120)
    parent = models.ForeignKey('Category', on_delete=models.SET_NULL,blank=True,null=True, related_name='categories')
    def __str__(self):
        return self.name

post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        fields = [

            'category',
            'title',
            'description',
            'post_image',
            'price',
            'adress',

        ]
        model = Post

post/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import Post,Category
from .forms import PostForm
from django.core.paginator import Paginator
from django.shortcuts import render



def post_index(request):
    post_list = Post.objects.all()
    query = request.GET.get('q')
    if query:
            post_list = post_list.filter(title__icontains=query)
    paginator = Paginator(post_list, 10)  # Show 25 contacts per page.

    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    return render(request, 'home.html', {'posts': posts})


def post_detail(request,id):
    post= get_object_or_404(Post, id=id)
    context = {
        'post': post,
    }
    return render(request, 'post/detail.html', context)


def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.yazar = request.user
        post.save()
        return HttpResponseRedirect(post.get_absolute_url())
    context = {
        'form': form,
    }

    return render(request, "form2.html", context)


def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.yazar = request.user
        post.save()
        return HttpResponseRedirect(post.get_absolute_url())
    context = {
        'form': form,
    }
    return render(request, "form2.html", context)


def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect("home")

def category_view(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'post/category.html', context)
def category_index_view(request, category_id):
    post_list = Post.objects.filter(Q(category=category_id) | Q(category__parent=category_id))
    query = request.GET.get('q')
    if query:
            post_list = post_list.filter(title__icontains=query)
    paginator = Paginator(post_list, 10)  # Show 25 contacts per page.

    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    return render(request, 'home.html', {'posts': posts})

def user_post_index(request):
    post_list = Post.objects.filter(yazar=request.user)
    query = request.GET.get('q')
    if query:
            post_list = post_list.filter(title__icontains=query)
    paginator = Paginator(post_list, 10)  # Show 25 contacts per page.

    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    return render(request, 'home.html', {'posts': posts})
# Create your views here.

templates/post/category.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <ul class="list-group">
        {% for c in categories %}
                <li class="list-group-item"><a class="link.danger" href="category/{{c.id}}" >{{c.name}}</a></li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/post/detail.html
{% extends 'base.html' %}

{% block body %}
<!--<div class="container">
<div class="row">
<div class="col-md-6">
<div class="mb-2"><img class="" src="{{post.post_image.url}}" width="400" height="400"></div>
</div>
<div class="col-md-6">
        <ul class="list-group">
            <h2 class=""><b>{{post.title.upper}}</b></h2>
            <h3><b>İlan Tarihi:</b> {{post.created_time}}</h3>
            <h3><b>Kategori:</b>{{ post.category }}</h3>
            <h3><b>Adres:</b>{{post.adress}}</h3>
            <h3><b>Fiyat:</b>{{ post.price }} ₺</h3>
            <b>İlan Açıklaması:</b>{{post.description}}
        </ul>
    </div>
</div>

</div> --!>
<div class="col offset-3">

        <div class="card text-white bg-dark mb-3" style="width: 45rem;">
        <img class="card-img-top" src="{{ post.post_image.url }}" alt="Card image cap" width="290" height="400">
         <div class="card-body">
             <h3 class="card-title text-center"><b>{{ post.title }}</b></h3>
             <h5 class="text-center">{{ post.category }}</h5>
             <p class="text-center">{{post.adress}}</p>
            <!-- <p class="card-text"><i>{{ post.description }}</i></p> --!>
            <p class="text-center">{{post.created_time}}</p>
             <h2 class="text-center"><b>{{ post.price }} ₺</b></h2>
             <p><b>Ürün Açıklaması:</b></p>
             <p><i>{{post.description}}</i></p>
             <p><b>İlanı Veren:<br> <a href="{% url 'users:userprofile' post.yazar %}"><img class="rounded-circle text-center" src="{{ post.yazar.avatar.url}}" width="40" height="40"></a><a class="link-danger" href="{% url 'users:userprofile' post.yazar %}"> {{post.yazar}}</a> </b></p>
             {% if request.user.is_authenticated %}
             {% if request.user == post.yazar %}
             <a href="{{post.id}}/update" class="btn btn-danger btn-lg align-bottom btn-sm" style="">İlanı Düzenle</a>
             <a href="{{post.id}}/delete" class="btn btn-danger btn-lg align-bottom btn-sm" style="">İlanı Sil</a>
             {% else %}
             <a href="{% url 'chats:start_chat' post.yazar %}" class="btn btn-danger btn-lg align-bottom btn-sm" style="">Mesaj Gönder</a>
             {% endif %}
             {% endif %}
         </div>
    </div>


    </div>











{% endblock %}