chat/urls.py
from django.urls import path


from . import views
app_name = 'chats'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    path('start_chat/<str:username>', views.start_chat, name="start_chat"),
]

cihadproje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from home.views import home_view
from post.views import post_index
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_index, name='home'),
    path('post/',include('post.urls')),
    path('users/', include('users.urls')),
    path('chat/', include('chat.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *


app_name = 'users'

urlpatterns = [
    path('profile', profile_view, name='profile'),
    path('login', login_view, name='login'),
    path('register', register_view, name='register'),
    path('logout', logout_view, name='logout'),
    path('logout', logout_view, name='logout'),
    path('edit', editprofile_view, name='edit'),
    path('<str:username>', user_profile_view, name='userprofile')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    GENDER_CHOICES = (
        ('Erkek','Erkek'),
        ('Kadın','Kadin'),
        ('Belirtilmedi', 'Belirtilmedi'),
    )
    bio = models.CharField(max_length=1000,null=True, blank=True,default="Henüz bir biyografi girilmedi...",verbose_name='Biyografi')
    gender = models.CharField(max_length=100, choices = GENDER_CHOICES, null=True, blank=True,default='Belirtilmedi',verbose_name='Cinsiyet')
    avatar = models.ImageField(null=True, blank=True, default='klasikpp.jpg',verbose_name='Profil Resmi')
    birthdate = models.DateField(null=True,blank=True,default='2000-01-01',verbose_name='Doğum Tarihi')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.auth import authenticate

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = "__all__"

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Kullanıcı adını veya şifreyi yanlış girdiniz!")
        return super(LoginForm, self).clean()

class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password1 = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label='Parola Doğrulama', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = [
            'username',
            'password1',
            'password2',
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Şifreler eşleşmiyor!")
        return password2

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model= CustomUser
        fields=['first_name','last_name','birthdate','avatar','bio','gender']

users/views.py
from django.shortcuts import render, redirect, Http404, get_object_or_404, HttpResponse
from .forms import LoginForm, RegisterForm, ProfileUpdateForm
from django.contrib.auth import authenticate, login, logout
from .models import CustomUser

def editprofile_view(request):
    form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('users:profile')

    return render(request, "users/form.html", {"form": form, 'title': 'Profili Düzenle'})
    def get_object(self):
        return self.request.user


def profile_view(request):
    if not request.user.is_authenticated:
        raise Http404()
    return render(request, 'users/profile.html')

def user_profile_view(request,username):
    user=get_object_or_404(CustomUser,username=username)
    return render(request, 'users/userprofile.html', {'user': user})

def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    return render(request, "users/form.html", {"form": form, 'title': 'Giriş Yap'})

def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        # user.is_staff = user.is_superuser = True
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        return redirect('home')

    return render(request, "users/form.html", {"form": form, 'title': 'Üye Ol'})

def logout_view(request):
    if not request.user.is_authenticated:
        raise Http404()
    logout(request)
    return redirect('home')

templates/users/editprofile.html
{% extends 'base.html' %}
    {% include 'header.html' %}

    {% block body %}
<div class="container">
<div class="row">
    <div class="col-md-6 offset-4">Burası profil düzenleme sayfası olacak.. :)</div>
</div>
</div>
    {% endblock %}

templates/users/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                <h1>{{title}}</h1>
                    {{ form|crispy }}
                    <button class="btn btn-dark">{{title}}</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
    {% include 'header.html' %}

    {% block body %}
    <div class="col-md-6 offset-3">
        <ul class="list-group">
            <h4><li class=" list-group-item list-group-item-dark mb-1 mt-2 text-center" aria-current="true"><b>Profil Bilgileri</b></li></h4>
            {% if request.user.avatar %}
            <div class="mb-2 text-center"><img class="rounded-circle" src="{{request.user.avatar.url}}" width="220" height="220"></div>
            {% endif %}
            <li class="list-group-item text-center"><b>Kullanıcı adı:</b> {{request.user.username}}</li>
            <li class="list-group-item text-center"><b>Ad:</b> {{request.user.first_name}}</li>
            <li class="list-group-item text-center"><b>Soyad:</b> {{request.user.last_name}}</li>
            <li class="list-group-item text-center"><b>Cinsiyeti</b> {{request.user.gender}}</li>
            <li class="list-group-item text-center"><b>Doğum Tarihi:</b> {{request.user.birthdate}}</li>
            <li class="list-group-item"><b>Biyografi:</b> {{request.user.bio}}</li>
        </ul>
        <div class="mt-2 mb-1 text-center">
            <a href="{% url 'users:edit' %}" class="btn btn-outline-dark" role="button" aria-pressed="true"><small>Profili Düzenle</small></a>
            <a href="{% url 'users:logout' %}" class="btn btn-outline-danger" role="button" aria-pressed="true"><small>Çıkış Yap</small></a>
        </div>
    </div>

    {% endblock %}

templates/users/userprofile.html
{% extends 'base.html' %}
    {% include 'header.html' %}

    {% block body %}
    <div class="col-md-6 offset-3">
        <ul class="list-group">
            <h4><li class=" list-group-item list-group-item-dark mb-1 mt-2 text-center" aria-current="true"><b>Profil Bilgileri</b></li></h4>
            {% if user.avatar %}
            <div class="mb-2 text-center"><img class="rounded-circle" src="{{user.avatar.url}}" width="220" height="220"></div>
            {% endif %}
            <li class="list-group-item text-center"><b>Kullanıcı adı:</b> {{user.username}}</li>
            <li class="list-group-item text-center"><b>Ad:</b> {{user.first_name}}</li>
            <li class="list-group-item text-center"><b>Soyad:</b> {{user.last_name}}</li>
            <li class="list-group-item text-center"><b>Cinsiyeti</b> {{user.gender}}</li>
            <li class="list-group-item text-center"><b>Doğum Tarihi:</b> {{user.birthdate}}</li>
            <li class="list-group-item"><b>Biyografi:</b> {{user.bio}}</li>
        </ul>
        {% if request.user.is_authenticated %}
        {% if request.user == user %}
        <div class="mt-2 mb-1 text-center">
            <a href="{% url 'users:edit' %}" class="btn btn-outline-dark" role="button" aria-pressed="true"><small>Profili Düzenle</small></a>
            <a href="{% url 'users:logout' %}" class="btn btn-outline-danger" role="button" aria-pressed="true"><small>Çıkış Yap</small></a>
        </div>
        {% else %}
        <div class="mt-2 mb-1 text-center">
        <a href="{% url 'chats:start_chat' user %}" class="btn btn-outline-dark" role="button" aria-pressed="true">Mesaj Gönder</a>
        </div>
        {% endif %}
        {% endif %}
    </div>

    {% endblock %}